### ISSUE TITLE
File data /a1910059.txt this file contains "XXXXXXX "| [bug] | [High Severity]

### ISSUE THREAD

**Issue by KamiKDS** [davmlaw/2024_assignment_5_adelaide_uni_bioinfo#101]
Hi David, 
Thanks for the project,
while going through the data set provided to my ID i found out that there is the presence of "XXXXXXX" in the lines 3 and 5 .

Commit hash: 987f34e7fe6bfe701bd09166f3d8158bfed5ccda
Commit date: 17-10-2024
Commit message: embrace best-of-breed web services

*Actual: In line 3, presence of "XXXXXXX" is observed once and in line 5 it is observed twice.

(line 3)-> imagine suddenly recognize worker XXXXXXX FORCE WHY protect.
(line 5)->second value look XXXXXXX fund XXXXXXX future upon.

*Expected: The presence of "XXXXXXX" is irrelevant and should be removed from lines 3 and 5.

(expected line 3)->imagine suddenly recognize worker  FORCE WHY protect.
(expected line 5)->second value look fund future upon.

A pull request will be created at the end.

Please look into this as this is classified as a high severity issue.
Thanks, 
Kartik.

**Comment by davmlaw** [comment]
No points lost but style hint is don't need to tag as [bug] | [High Severity]

If you really want to distinguish a bug you can do that via label as I just did - doing it that way means you can search by label
