### ISSUE TITLE
"XXXXXXX" found in data/a1899345 (High severity issue)

### ISSUE THREAD

**Issue by arunkiran1205** [davmlaw/2024_assignment_5_adelaide_uni_bioinfo#104]
Hi David,
While going through the data I found certain issues that needs to be rectified.

Commit hash: 89dd1955faad0c0490772794b3de8ab6605e6eeb
Commit date: 17-10-2024
Commit message: redefine innovative solutions

"XXXXXX" was found in line 1 of the data
Actual: catch less CHARGE environmental. XXXXXXX system SCIENTIST investment XXXXXXX AVOID XXXXXXX former language budget design.

Expected : catch less CHARGE environmental. system SCIENTIST investment  AVOID former language budget design.

A pull request will be created when fixed.

Thank You,
Arun Kiran

**Comment by davmlaw** [comment]
Could be more polite. Bit harsh to start out with "needs to be rectified" with no acknowledgement of their hard work for someone doing free work for you
