### ISSUE TITLE
Uppercase letters found in data/a1899345

### ISSUE THREAD

**Issue by arunkiran1205** [davmlaw/2024_assignment_5_adelaide_uni_bioinfo#105]
Hi David,
While going through the data I found certain issues that needs to be rectified.

Commit hash: 89dd1955faad0c0490772794b3de8ab6605e6eeb
Commit date: 17-10-2024
Commit message: redefine innovative solutions

Uppercase letters was found in line 1 of the data
Actual: catch less CHARGE environmental. XXXXXXX system SCIENTIST investment XXXXXXX AVOID XXXXXXX former language budget design.

Expected :catch less charger environmental. XXXXXXX system scientist investment XXXXXXX avoid XXXXXXX former language budget design..

Thank You,
Arun Kiran

**Comment by davmlaw** [comment]
Git hash correct, but date of bug was 23/9

Typo in expected "charge" -> "charger" (typos don't matter anywhere else, but here they do)
