### ISSUE TITLE
High Severity Bug: Unexpected 'XXXXXXX' Insertions in a1900426

### ISSUE THREAD

**Issue by Kexin190** [davmlaw/2024_assignment_5_adelaide_uni_bioinfo#113]
Hi David,
Hope you are well when you receive the message. I found some minor errors in processing the file a1900426.txt. Three "XXXXXXX" were accidentally inserted in one sentence, which affected the readability and integrity of the data.

Commit message: "Initial data upload with student number assignments"

Actual: XXXXXXX themselves peace argue. DEVELOPMENT reveal XXXXXXX agreement XXXXXXX marriage myself before.

Expected: themselves peace argue. development reveal agreement marriage myself before.

I plan to submit a pull request after correcting the problem.

Thank you,
Kexin Wang

**Comment by davmlaw** [comment]
message given was for initial commit, the error was inserted with commit 8207983b1b3b16fe3ee7d22a4435e1d3c41f3400 message was "extend turn-key supply-chains"
