### ISSUE TITLE
High Severity Bug "XXXXXXX" in data/a1873151.txt

### ISSUE THREAD

**Issue by QingkunLi187** [davmlaw/2024_assignment_5_adelaide_uni_bioinfo#115]
Dear Maintainer,

Thank you for maintaining this project. I have identified a high-severity issue in the file 'data/a1873151.txt', where "XXXXXXX" has been inserted in multiple locations. I would like to provide a fix for this issue.

The issue was introduced in commit 4f7dfd3828a5eb45474bd894e61caffc93d7ea7a.

Expected:
The line should not contain XXXXXXX, and only one space between the words should exist.

Actual:
1. certainly XXXXXXX hard raise action for clearly trip.
2. someone environmental leg XXXXXXX future first son commercial.
3. building XXXXXXX these clear republican experience.

I plan to submit a pull request to fix this issue shortly.

Best regards,
Qingkun Li

**Comment by davmlaw** [comment]
Commit was right but were supposed to give message: enable B2B functionalities
