### ISSUE TITLE
[High Severity Bug] in the file data/a1955686.txt 

### ISSUE THREAD

**Issue by Limon5466** [davmlaw/2024_assignment_5_adelaide_uni_bioinfo#122]
Dear Maintainer,

Thank you for all the work you put into maintaining this project. Really appreciate all your effort.
It would appear I have found a problem in the file a1955686.txt has occurrences of 'XXXXXXX. 

Line1 
**Expected:** i reveal later TOGETHER. early spring process hotel SIMPLY.
**Actual:** i reveal XXXXXXX later TOGETHER. early spring process XXXXXXX hotel SIMPLY.

Line2
**Expected:**  early spring process hotel SIMPLY.
**Actual:**  early spring process XXXXXXX hotel SIMPLY.

Line 3
**expected:** large garden add back. ATTORNEY do company mean myself government.
**Actual:** XXXXXXX large garden add back. ATTORNEY do company mean myself government.

I plan on submitting a pull request to address this bug.

Best regards
MD Kamruzzaman Limon

**Comment by davmlaw** [comment]
commit log message was "drive wireless action-items"
