### ISSUE TITLE
Low Severity Issue: Uppercase Formatting Bug in a1955686.txt

### ISSUE THREAD

**Issue by Limon5466** [davmlaw/2024_assignment_5_adelaide_uni_bioinfo#124]
Thank you for all the work you put into maintaining this project. Really appreciate all your effort.
There  is a low-severity bug related to improper uppercase formatting of specific words in a1955686.txt. This formatting error affects readability, causing certain words to be capitalized when they should not be.

Date of Commit: 10/18/2024

Line:
**Expected:** i reveal XXXXXXX later together.
**Actual:** i reveal XXXXXXX later TOGETHER.

Line: 
**Expected:** early spring process XXXXXXX hotel simply.
**Actual:** early spring process XXXXXXX hotel SIMPLY.

Line: 
**Expected:** attorney do company mean myself government.
**Actual**: ATTORNEY do company mean myself government.

I plan on submitting a pull request to address this bug.

Best regards
MD Kamruzzaman Limon

**Comment by davmlaw** [comment]
Git hash ed0b20adf2973242f642cceba040faa9c5daeea0
