### ISSUE TITLE
Low severity issue: letter given in UPPERCASE in file a1904204.txt

### ISSUE THREAD

**Issue by ghost** [davmlaw/2024_assignment_5_adelaide_uni_bioinfo#134]
Hi, 
Thank you for maintaining this repository.

Issue:  letters given in UPPERCASE in the first line.
"LEAST RATHER HOWEVER national within after. toward his imagine everyone arrive single need approach."

commit: f1b2c24722bbc1315f6bf3511f0c90304e4bfb6b
Author: Dave Lawrence <davmlaw@gmail.com>
Date:   Mon Sep 23 16:38:52 2024 +0930

Actual issue: 
the words 'LEAST' 'RATHER' and 'HOWEVER' are in the upper case.
"LEAST RATHER HOWEVER national within after. toward his imagine everyone arrive single need approach"

Expected behavior:
the letters should be in the lowercase.
'least rather however national within after. toward his imagine everyone arrive single need approach'
 I am planning to submit a pull request to solve this issue.

**Comment by davmlaw** [comment]
Commit was 1c655ef90dce7f66a2eebc8a45d7c33ff9b4a3b "syndicate granular applications"

The one you gave was for file a1954027.txt
