### ISSUE TITLE
High Severity issue: XXXXXXX placeholder issue a1904204.txt

### ISSUE THREAD

**Issue by ghost** [davmlaw/2024_assignment_5_adelaide_uni_bioinfo#135]
Hi,
Thank you for maintaining the repository .
The issue noticed in the file 'a1904204.txt'

Issue: line 1 has an issue "LEAST RATHER HOWEVER national within XXXXXXX after. toward his imagine XXXXXXX everyone arrive single XXXXXXX need approach". 
The placeholder XXXXXXX is in different places and this need to be changed.

Commit: 176493af9881d119ada3a2bb9cb9bf82475b33cc
       Author: Dave Lawrence <davmlaw@gmail.com>
       Date:   Mon Sep 23 16:50:54 2024 +0930

Actual Behaviour: 
the placeholder XXXXXXX will be visible.

LEAST RATHER HOWEVER national within XXXXXXX after
toward his imagine XXXXXXX 
everyone arrive single XXXXXXX need approach

Expected Behaviour:
XXXXXXX placeholder should be removed.

I am planning to submit pull request for the issue.

Thankyou 
Greeshma Sivaprasad

**Comment by davmlaw** [comment]
Commit was 41c655ef90dce7f66a2eebc8a45d7c33ff9b4a3b "syndicate granular applications"
