### ISSUE TITLE
issue: high severity XXXXXXX placeholder a1904204

### ISSUE THREAD

**Issue by Greeshma13524** [davmlaw/2024_assignment_5_adelaide_uni_bioinfo#137]
Hi,
Thank you for maintaining the repository .
The issue noticed in the file 'a1904204.txt'

Issue: line 1 has an issue "LEAST RATHER HOWEVER national within XXXXXXX after. toward his imagine XXXXXXX everyone arrive single XXXXXXX need approach".
The placeholder XXXXXXX is in different places and this need to be changed.

Commit: 24f62cc2 
               author: Dave Lawrence     
                 Date:  2024-09-23 16:34:56 +0930

Actual Behaviour:
the placeholder XXXXXXX will be visible.

LEAST RATHER HOWEVER national within XXXXXXX after
toward his imagine XXXXXXX
everyone arrive single XXXXXXX need approach

Expected Behaviour:
XXXXXXX placeholder should be removed.

I am planning to submit pull request for the issue.

Thankyou
Greeshma

**Comment by davmlaw** [comment]
Commit was 41c655ef90dce7f66a2eebc8a45d7c33ff9b4a3b	syndicate granular applications
