### ISSUE TITLE
issue: low severity uppercase letter in file a1904204.txt

### ISSUE THREAD

**Issue by Greeshma13524** [davmlaw/2024_assignment_5_adelaide_uni_bioinfo#138]
Hi,
Thank you for maintaining this repository.

Issue: letters given in UPPERCASE in the first line.
"LEAST RATHER HOWEVER national within after. toward his imagine everyone arrive single need approach."

commit: 24f62cc2 
                Author:Dave Lawrence      
                Date: 2024-09-23 16:34:56 +0930  3) 

the words 'LEAST' 'RATHER' and 'HOWEVER' are in the upper case.
"LEAST RATHER HOWEVER national within after. toward his imagine everyone arrive single need approach"

Expected behavior:
the letters should be in the lowercase.
'least rather however national within after. toward his imagine everyone arrive single need approach'
I am planning to submit a pull request to solve this issue.

**Comment by davmlaw** [comment]
Commit was 41c655ef90dce7f66a2eebc8a45d7c33ff9b4a3b	syndicate granular applications
