### ISSUE TITLE
High severity bugs in file ”data/a1876866.txt” with ”XXXXXXX” Insertion  

### ISSUE THREAD

**Issue by JunsongZ** [davmlaw/2024_assignment_5_adelaide_uni_bioinfo#140]
Dear former maintainer davmlaw, 

First of all, thank you for your contribution to this project. I found high-severity bugs of the XXXXXXX insertions in data/a1876866.txt.   

Commit SHA:  757ed4af20dd0ca9d7d7d3026532249a6e54ac5b 

Expected_Line_7:mouth run EVERY job level. daughter LEFT PATTERN similar month tough play.

Actual_Line_7:mouth run EVERY job level. daughter LEFT XXXXXXX PATTERN similar month tough play.  

Expected_Line_9: score level hour question hit beat. to ahead yeah space strategy past friend. growth not finally evidence suddenly factor surface industry.

Actual_Line_9:score level hour XXXXXXX question hit beat. XXXXXXX to ahead yeah space strategy past friend. growth not finally evidence suddenly factor surface industry.

I plan to submit a pull request to fix it.

**Comment by davmlaw** [comment]
Commit is correct but asked for message which  was "incubate revolutionary web-readiness"
