### ISSUE TITLE
Low severity bugs in file ”data/a1876866.txt” with the lower case world replaced with the upper case word.

### ISSUE THREAD

**Issue by JunsongZ** [davmlaw/2024_assignment_5_adelaide_uni_bioinfo#141]
Dear former maintainer davmlaw, 

First of all, thank you for your contribution to this project. I found low severity bug of lower case world replaced with the upper case word in data/a1876866.txt.  

Commit SHA:  757ed4af20dd0ca9d7d7d3026532249a6e54ac5b 

Expected_Line_7: mouth run every job level. daughter left XXXXXXX pattern similar month tough play.

Actual_Line_7:mouth run EVERY job level. daughter LEFT XXXXXXX PATTERN similar month tough play.

**Comment by davmlaw** [comment]
commit good but date missing - was 23/9/24
