### ISSUE TITLE
High Severity Bug found in "data/a1853428.txt" with an insertion of "XXXXXXX"

### ISSUE THREAD

**Issue by a1853428** [davmlaw/2024_assignment_5_adelaide_uni_bioinfo#142]
Hello davmlaw,
Thank you for you contributions to this project. I believe I have found a high severity bug in the file "data/a1853428.txt" with an insertion of "XXXXXXX". 

Commit: d15e4a4

Expected Line 1: campaign INTERNATIONAL each would. than individual loss contain. simple never our manage.

Actual Line 1: XXXXXXX campaign XXXXXXX INTERNATIONAL XXXXXXX each would. than individual loss contain. simple never our manage. 

I will submit a pull request to rectify this issue.

Kind regards

**Comment by davmlaw** [comment]
missing commit message: "revolutionize open-source models"
