### ISSUE TITLE
High Severity Bug: XXXXXXX placeholder in data/a1749842.txt

### ISSUE THREAD

**Issue by a1749842SH** [davmlaw/2024_assignment_5_adelaide_uni_bioinfo#146]
Hello davmlaw,
Thank you for maintaining this project. I have found a high severity bug in data/a1749842.txt where the placeholders XXXXXXX are present.

This issue was introduced in commit 273bdf40 on 2024-09-23.

Expected lines:
Line 1: "Recent time mrs movie rate describe tax before."
Line 11: "look quite good CENTRAL media she might call."

Affected Lines:
Line 1: "XXXXXXX time mrs movie rate describe tax before."
Line 11: "look XXXXXXX good CENTRAL media she XXXXXXX call."

I would be happy to resolve this and submit a pull request shortly.

**Comment by davmlaw** [comment]
Git hash correct but missing commit message "drive enterprise communities"
