### ISSUE TITLE
File document/a1851451.txt contains UPPER_CASE_WORD insertions

### ISSUE THREAD

**Issue by aklout** [davmlaw/2024_assignment_5_adelaide_uni_bioinfo#41]
Hi there!

Thank you for all your work on this project! It has been so helpful.

While observing the file, I think I have found low severity UPPERCASES issues on lines 5. The commit that introduced the issues was https://github.com/davmlaw/2024_assignment_5_adelaide_uni_bioinfo/commit/623532a735043b2d4e3c0acc87fe4bdd846ee1af, file named "extend extensible paradigms," made on the 23rd of September 2024.

The lines expected to read as;
Line 5 - "charge environmental car leader executive great gas. research loss lead since table court."

However, it actual lines read as;
Line 5 - "charge ENVIRONMENTAL XXXXXXX CAR leader executive great gas. RESEARCH loss lead since"

I plan on submitting a pull request once the issue is remediated by reverting the uppercase letters to lower case from the file.

Thank you again!

**Comment by davmlaw** [comment]
looks good, lost 1 point as commit should have been 5581dc9d6156206fc47385c3480a0927d21a4d95 (comment is right) that was for different file a1851176.txt
