### ISSUE TITLE
File data/a1947736.txt contains' XXXXXXX'  bug (high severity issue)

### ISSUE THREAD

**Issue by 1999921wjkYY** [davmlaw/2024_assignment_5_adelaide_uni_bioinfo#55]
Hi Dave,
Thank you heaps for your project and the efforts you've put in maintaining it!

First, I want to thank you for all the work you’ve put into this project. It has been incredibly helpful for my work, and I really appreciate your effort in maintaining it.

While working with the a1947736.txt file, I noticed that XXXXXXX have been added randomly to some position in line 1 and line 11. I've outlined the details of this issue below.

Commit hash: https://github.com/davmlaw/2024_assignment_5_adelaide_uni_bioinfo/commit/6a583cb865f82f77931b628a93327218e1717c93
Commit date: 15/10/2024
Commit message: architect bricks-and-clicks content

Actual Text
L1: debate decision pull XXXXXXX city road. out company look stage security across upon they. article find another laugh.
L11: ORDER FROM XXXXXXX WIDE west. push goal check XXXXXXX nature good lawyer late.

Expected Text
L1: debate decision pull city road. out company look stage security across upon they. article find another laugh.
L11: order from wide west. push goal check nature good lawyer late.

I plan to submit a pull request once I have replaced the uppercase words with lowercase ones in the file.

Thank you again,
Yu Yang

**Comment by davmlaw** [comment]
commit message should have been "synthesize visionary paradigms"

"architect bricks-and-clicks content" was for a1865749, commit d711b202e3e8669e4bef78ccfa8931b78432a472
