### ISSUE TITLE
File data/a1909154.txt contains UPPERCASE bug (Low severity issue)

### ISSUE THREAD

**Issue by ZhangDini** [davmlaw/2024_assignment_5_adelaide_uni_bioinfo#57]
Dear Maintainer,

Firstly, I’d like to express my appreciation for your work on this project. It has been incredibly valuable to my research.

While reviewing the file a1909154.txt, I noticed that some words are written in UPPERCASE when they should be in lowercase. I've outlined the details of this issue below.

Commit hash: [16420df](https://github.com/davmlaw/2024_assignment_5_adelaide_uni_bioinfo/commit/16420df838405e514234bb53a71f6e720c8fda31#diff-be293a0a945940bef9723b727a69b41024487d5dc34eb1a8639bf90888e1796eL7)
Commit date: 15/10/2024
Commit message: architect bricks-and-clicks content

Line 3:
Actual: determine BOARD investment religious investment prepare central. my early reality year suddenly INVOLVE from from. XXXXXXX finish BETWEEN change XXXXXXX space world. 
Expected: determine board investment religious investment prepare central. my early reality year suddenly involve from from. XXXXXXX finish between change XXXXXXX space world.

I plan to submit a pull request to address this. Thank you once again for your hard work.

Best regards,
Dini Zhang

**Comment by davmlaw** [comment]
git hash correct but date should have been 23/9/24 (can see from hovering over it)
