### ISSUE TITLE
File data/a1947736.txt contains UPPERCASE bug (low severity issue)

### ISSUE THREAD

**Issue by 1999921wjkYY** [davmlaw/2024_assignment_5_adelaide_uni_bioinfo#58]
Hi Dave,
Thank you for your project, it has helped me out a ton!

Above all, I would like to express my gratitude for all your works on this project. It has been extremely useful to me. While working on the file a1947736.txt, where certain words are incorrectly written in UPPERCASE. I have provided the details below for your reference: Here is a breakdown of the bug for your understanding and convenience.

Commit hash: https://github.com/davmlaw/2024_assignment_5_adelaide_uni_bioinfo/commit/6a583cb865f82f77931b628a93327218e1717c93

Commit date: 15/10/2024

Commit message: architect bricks-and-clicks content

Actual Text
L11: ORDER FROM XXXXXXX WIDE west. push goal check XXXXXXX nature good lawyer late.

Expected Text
L11: order from wide west. push goal check nature good lawyer late.

I plan to submit a pull request once I have replaced the uppercase words with lowercase ones in the file.

Thank you again,
Yu Yang

**Comment by davmlaw** [comment]
git hash correct but date should have been 23/9/24 (can see from hovering over it)
