### ISSUE TITLE
Fix Low Severity UPPERCASE Formatting in data/a1893982.txt

### ISSUE THREAD

**Issue by 3991Mansi** [davmlaw/2024_assignment_5_adelaide_uni_bioinfo#68]
Hello, I hope this message finds you well. Thankyou for maintaining this valuable project. While working with the repository, I noticed an error involving a low-severity UPPERCASE formatting issue in the file data/a1893982.txt , which seems to have been inadvertently included.

The error was introduced in the following commit in line 5:
commit message: 'drive magnetic applications'

commit SHA: [7c894c7b](https://github.com/davmlaw/2024_assignment_5_adelaide_uni_bioinfo/commit/7c894c7b77d3445493a20616eb2da5f75d5ec4a1)

Expected:
(line 5) approach bag goal lay analysis they. baby from together this XXXXXXX hour today. test XXXXXXX recent field system.

Actual:
(line 5) approach bag GOAL LAY analysis they. baby from together this XXXXXXX hour today. TEST XXXXXXX recent field system.

I believe that correcting this issue will enhance its reliability. I plan to address this bug and will submit a pull request soon for your review.

Thank you for your attention to this matter, and for your ongoing efforts in maintaining such a valuable resource.

Regards,
Mansi Rawal

**Comment by davmlaw** [comment]
Date was 23/10
