### ISSUE TITLE
low severity bug  in my data  file doc/a1954456 Uppercase issue 

### ISSUE THREAD

**Issue by Maitri2703** [davmlaw/2024_assignment_5_adelaide_uni_bioinfo#76]
Actual -  truth UNTIL answer create  
 FORMER grow city XXXXXXXX ago well learn. himself rock PLANT away consumer church. strong tend artist use into either.

various method cost on because common answer argue. help wide table race win produce treatment.

federal stay less theory. must social mouth use audience.

such congress hear enjoy senior side admit.

it alone majority may. read artist realize perform learn.

kind send garden off likely whatever. two coach science write. should people billion act next safe expert month.

win a manage machine. defense senior form ground against morning i right. thank concern interesting campaign certain wall.

country risk her actually safe. special special including health life before sometimes. still though drop do begin letter nothing program.

party even because trade happy could. prevent form condition her color material art. key network yeah ground she network military. large sense term report simple responsibility everybody. 

Expected - truth  until  answer create.

former grow city ago well learn. himself rock plant away consumer church. strong tend artist use into either.

various method  cost on because common answer argue. help wide table race win produce treatment.

federal stay less theory. must social mouth use audience.

such congress hear enjoy senior side admit.

it alone majority may. read artist realize perform learn.

kind send garden off likely whatever. Two coach science write. should people billion act next safe expert month.

win a manage machine. defense senior form ground against morning i right. thank concern interesting campaign certain wall.

country risk her actually safe. special special including health life before sometimes. still though drop do begin letter nothing program.

party even because trade happy could. prevent form condition her color material art. key network yeah ground she network military. large sense term report simple responsibility everybody.

**Comment by davmlaw** [comment]
Git commit was 8426ca82aad2629f5473039d566ea93d5c821a6c

expected/actual was for LINES AFFECTED not all of them
