### ISSUE TITLE
High severity issue: data/a1901379.txt contains ‘XXXXXXX’

### ISSUE THREAD

**Issue by Noir-ink-codes** [davmlaw/2024_assignment_5_adelaide_uni_bioinfo#79]
Hello there, 

Thanks for the code. It has really helped me with my work. 
I wanted to point out that have found a commit which has introduced high severity issues  containing 'XXXXXXX' within the file data/a1901379.txt in line 5. The commit had the following commit message:

Commit message: mesh virtual technologies
commit ID: 8a2ff77
Commit date: Sep 23, 2024

Following are the actual and changed lines:
line 5 actual:
LATER mr resource enjoy without purpose than. MAYBE XXXXXXX truth campaign XXXXXXX image XXXXXXX another bed particular interesting. newspaper COLOR movie east story.

line 5 changed:
LATER mr resource enjoy without purpose than. MAYBE truth campaign image another bed particular interesting. newspaper COLOR movie east story.

I will attempt to solve this issue, and I plan to submit a pull request.

Thank you for maintaining this repository, and I wish to contribute to improve it.

Regards,
Kuhu Kinnori

**Comment by davmlaw** [comment]
slight deduction in expected/actual as lines changed should be "actual" as reporting error, not doing fix
