### ISSUE TITLE
High Severity Bud in a1894991.txt - insertion of text xxxxxxx

### ISSUE THREAD

**Issue by Brijit27** [davmlaw/2024_assignment_5_adelaide_uni_bioinfo#95]
Firstly, Thank you for maintaining this project. 
I have noticed some issues in the file 'a1894991.txt' 

Issue: 
Line 1: The placeholder 'xxxxxxx' is used in different places. And it needs to be replaced with the appropriate content.
 "I today xxxxxxx manage position xxxxxxx little."
"xxxxxxx member related other life behavior."

The issue was introduced in the "ab2988d4" commit 
Commit message: "Initial commit"

Expected Behavior:
1. The 'xxxxxxx' placeholder should be replaced with meaningful text.

Actual Behavior:
1. The placeholder will be still present
"I today xxxxxxx manage position xxxxxxx little."
"xxxxxxx member related other life behavior."

I am planning to submit a pull request to fix this issue. 

Thank you,
Bella Brijit

**Comment by davmlaw** [comment]
Git commit message was: enable granular info-mediaries

slight deduction in expected / actual -  ideally give examples, but "should be deleted" is more accurate
