### ISSUE TITLE
Low Severity Bug - UPPERCASE Bug in a1894991.txt

### ISSUE THREAD

**Issue by Brijit27** [davmlaw/2024_assignment_5_adelaide_uni_bioinfo#96]
Firstly, Thank you for maintaining this project!

There are some issues in the "a1894991.txt" file. Some words are written incorrectly using  UPPERCASE letters in this file. 
The issue occurs on the following line:
Line 2: "rise COLOR yet hotel region area. focus weight daughter FACT special whole be."

The issue was raised in the Commit 'ab2988d4'.
Date and Git Hash of the commit: 2024-10-17 08:21:55 +0530 

Expected Behavior:
The words COLOR and FACT should be written in lowercase letters.
"rise color yet hotel region area. focus weight daughter fact special whole be."

Actual Behavior:
The words COLOR and FACT are written in uppercase letters.
"rise COLOR yet hotel region area. focus weight daughter FACT special whole be."

I am planning to submit a pull request to resolve this issue.

**Comment by davmlaw** [comment]
Commit should have been 195db973dfa9649e45e3a2d6d8aa7452e754fb67 - 23/9/2024

to check if commit exists in project, when you enter it in an issue it should generate a link
